// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAamFDRlQN2dDWoxOkp66iE5S7b5KssoSs',
    appId: '1:61069233213:web:a6a94a34d3fc85524fee54',
    messagingSenderId: '61069233213',
    projectId: 'halo-fb212',
    authDomain: 'halo-fb212.firebaseapp.in',
    storageBucket: 'halo-fb212.firebasestorage.app',
    measurementId: 'G-2T3ZCM3BF1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-JvudW2bdu7KnKOl-cMTKHqZYrqF0ia8',
    appId: '1:61069233213:android:488a5691a5034b494fee54',
    messagingSenderId: '61069233213',
    projectId: 'halo-fb212',
    storageBucket: 'halo-fb212.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUBDxM5AdZ-DhuYOJUgaTQ_Dgnzefa8a8',
    appId: '1:61069233213:ios:19bf47cabf6dc46a4fee54',
    messagingSenderId: '61069233213',
    projectId: 'halo-fb212',
    storageBucket: 'halo-fb212.firebasestorage.app',
    iosBundleId: 'in.urss.classic1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUBDxM5AdZ-DhuYOJUgaTQ_Dgnzefa8a8',
    appId: '1:61069233213:ios:19bf47cabf6dc46a4fee54',
    messagingSenderId: '61069233213',
    projectId: 'halo-fb212',
    storageBucket: 'halo-fb212.firebasestorage.app',
    iosBundleId: 'in.urss.classic1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAamFDRlQN2dDWoxOkp66iE5S7b5KssoSs',
    appId: '1:61069233213:web:0f2cab072b2242134fee54',
    messagingSenderId: '61069233213',
    projectId: 'halo-fb212',
    authDomain: 'halo-fb212.firebaseapp.in',
    storageBucket: 'halo-fb212.firebasestorage.app',
    measurementId: 'G-3HVJM7EHRP',
  );
}
